[package]
name = "mandelbrot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
angular-units = "0.2.4"
minifb = "0.24.0"
num = "0.4.0"
prisma = "0.1.1"
